// Deploying the worker.
//
// Everything goes through wrangler rather than the REST API, because wrangler
// works with browser sign-in — so nobody has to create an API token by hand.
// The config is generated into a temporary file that is deleted afterwards; it
// contains no secrets (those are uploaded separately as Worker secrets) but it
// does contain account-specific ids, and it should not linger in a git
// checkout.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { wrangler } from './api/cloudflare.mjs';

const SHIM = 'immich-api-shim';

/** Plain, non-secret variables the worker reads. */
export function workerVars(env) {
  return {
    SELF_HOST: '1',
    APP_IDENTIFIER: 'selfhost',
    // Their Firebase project — never ours.
    FIREBASE_API_KEY: env.FIREBASE_API_KEY || '',
    FIREBASE_PROJECT_ID: env.FIREBASE_PROJECT_ID || '',
    // Deliberately empty: the hosted value points at a relay worker of ours,
    // and with D1 bound the worker relays through itself instead.
    TELEGRAM_PROXY: '',
    ALLOWED_ORIGINS: env.ALLOWED_ORIGINS || 'http://localhost:5173',
    EXTERNAL_DOMAIN: env.DASHBOARD_URL || '',
    UPDATE_REPO: env.UPDATE_REPO || 'myrosama/DaemonClient',
    BUILD_VERSION: env.BUILD_VERSION || '0.0.0',
  };
}

function toml(env, buildVersion) {
  const vars = workerVars({ ...env, BUILD_VERSION: buildVersion });
  const lines = [
    '# Generated by the DaemonClient setup. Safe to delete.',
    `name = "${env.WORKER_NAME}"`,
    'main = "src/index.ts"',
    'compatibility_date = "2024-09-23"',
    'compatibility_flags = ["nodejs_compat"]',
    '',
    '[vars]',
    ...Object.entries(vars).map(([k, v]) => `${k} = ${JSON.stringify(String(v))}`),
    '',
    '[[d1_databases]]',
    'binding = "DB"',
    `database_name = ${JSON.stringify(env.D1_DATABASE_NAME || 'daemonclient-db')}`,
    `database_id = ${JSON.stringify(env.D1_DATABASE_ID)}`,
    '',
  ];
  return lines.join('\n');
}

/** Deploy the worker from source. Returns its workers.dev URL if known. */
export async function deployWorker(repoRoot, env, buildVersion, { onProgress } = {}) {
  const shimDir = path.join(repoRoot, SHIM);
  if (!fs.existsSync(path.join(shimDir, 'node_modules'))) {
    throw new Error(`dependencies are missing — run: cd ${SHIM} && npm install`);
  }

  // A unique name keeps concurrent runs and leftovers from colliding.
  const configPath = path.join(shimDir, `.wrangler-selfhost-${process.pid}.toml`);
  fs.writeFileSync(configPath, toml(env, buildVersion), { mode: 0o600 });

  const ctx = { cwd: shimDir, apiToken: env.CLOUDFLARE_API_TOKEN, accountId: env.CLOUDFLARE_ACCOUNT_ID };
  try {
    onProgress?.('Uploading the worker');
    const out = await wrangler(['deploy', '--config', configPath], ctx);

    onProgress?.('Storing secrets');
    // Secrets go up separately so they never appear in a config file, in the
    // dashboard's variable list, or in a process argument list.
    for (const [name, value] of [
      ['SESSION_SECRET', env.SESSION_SECRET],
      ['ENCRYPTION_MASTER_KEY', env.STORAGE_KEY],
    ]) {
      if (!value) continue;
      await putSecret(shimDir, configPath, ctx, name, value);
    }

    const url = out.match(/https:\/\/[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev/i)?.[0] || null;
    return url;
  } finally {
    try { fs.unlinkSync(configPath); } catch {}
  }
}

/** `wrangler secret put` reads the value from stdin, which keeps it out of the
 *  process table where `ps` would show it. */
async function putSecret(cwd, configPath, ctx, name, value) {
  const { execFile } = await import('node:child_process');
  await new Promise((resolve, reject) => {
    const child = execFile(
      'npx',
      ['wrangler', 'secret', 'put', name, '--config', configPath],
      {
        cwd,
        env: {
          ...process.env,
          WRANGLER_SEND_METRICS: 'false',
          ...(ctx.apiToken ? { CLOUDFLARE_API_TOKEN: ctx.apiToken } : {}),
          ...(ctx.accountId ? { CLOUDFLARE_ACCOUNT_ID: ctx.accountId } : {}),
        },
      },
      (err) => (err ? reject(new Error(`could not store ${name}: ${String(err.message).split('\n')[0]}`)) : resolve()),
    );
    child.stdin.write(value);
    child.stdin.end();
  });
}

/** Build the worker bundle (used by the update path to report its size and to
 *  fail early if the source does not compile). */
export async function buildCheck(repoRoot) {
  const shimDir = path.join(repoRoot, SHIM);
  await wrangler(['deploy', '--dry-run', '--outdir', 'dist'], { cwd: shimDir });
  const out = path.join(shimDir, 'dist', 'index.js');
  return fs.existsSync(out) ? fs.statSync(out).size : 0;
}

/** The canonical schema, read from the deployment service so a self-hosted
 *  install creates exactly the same tables as a hosted one. */
export function readMigrationSql(repoRoot) {
  const source = path.join(repoRoot, 'deployment-service', 'src', 'index.ts');
  const text = fs.readFileSync(source, 'utf8');
  const grab = (name) => {
    const start = text.indexOf(`const ${name} = \``);
    if (start < 0) return '';
    const from = text.indexOf('`', start) + 1;
    const to = text.indexOf('`', from);
    return to > from ? text.slice(from, to) : '';
  };
  const photos = grab('MIGRATION_SQL');
  if (!photos) throw new Error('could not read MIGRATION_SQL from deployment-service');
  return [photos, grab('DRIVE_MIGRATION_SQL')].filter(Boolean).join('\n');
}

export function splitSql(sql) {
  return sql.split(';').map((s) => s.trim()).filter((s) => s && !s.startsWith('--'));
}
